---
title: "BUECI Colors"
author: "Kiefer Fallin"
date: "4/6/2023"
output: html_document
---


```{r}
library(ggplot2)
library(plyr)
library(dplyr)
library(lubridate)
library(tidyr)
library(gridExtra)
library(forcats)
library(splitstackshape) 
library(naniar)
library(RColorBrewer)
library(clock)
```


```{r}
grndtmp619_920=read.csv("/Users/kieferfallin/Desktop/Research/Season_GRNDTMP_6_19_22_9_20_22_2022_09_21_16_19_26_UTC_1.csv")
names(grndtmp619_920) <- sub("....C..RX3000_BRW1", "", names(grndtmp619_920))
names(grndtmp619_920) <- sub("....C..RX3000_BRW4", "", names(grndtmp619_920))
names(grndtmp619_920) <- sub("....C..RX3000_BRW5", "", names(grndtmp619_920))
names(grndtmp619_920) <- sub("....C..RX3000_BRW6", "", names(grndtmp619_920))
names(grndtmp619_920) <- sub(".RXW.GP6.", "", names(grndtmp619_920))
grndtmp619_920$Date <-as.POSIXct(grndtmp619_920$Date,format="%m/%d/%y %H:%M",tz="UTC")
grndtmp619_920 = grndtmp619_920[,-14]
```

```{r}
grndtmp = gather(grndtmp619_920, variable, response, Temperature.21198259.21206939.7:Temperature.21401803.21398591.17) %>%
  filter(!is.na(response)) %>%
  mutate(variable = fct_inorder(variable))
dfgrndtemp= cSplit(grndtmp, 'variable', sep=".", direction = "wide") 
colnames(dfgrndtemp)[3] <- ("value")
colnames(dfgrndtemp)[5:7] <- c("station", "sensor", "depth")
dfgrndtemp$V212 <- NULL
dfgrndtemp$V213 <- NULL
dfgrndtemp$variable_1 <- NULL
dfgrndtemp$depth <- as.factor(as.character(dfgrndtemp$depth))
dfgrndtemp$sensor <- as.factor(as.character(dfgrndtemp$sensor))
dfgrndtemp$station <- as.factor(dfgrndtemp$station)
dfgrndtemp$station <- revalue(dfgrndtemp$station, c("21198259" = "TNHA", "21401800" = "BUECI", "21401801" = "SSMH", "21401803" = "BEO")) #renaming the stations
dfgrndtemp$sensor <- revalue(dfgrndtemp$sensor, c("21398585" = "BUECI-BASE", "21398590" = "BUCEI-SA", "21398583" = "BUECI-SB", "21393042" = "BUCEI-SC", "21398584" = "BUCEI-SD", "21398579" = "BUCEI-SE", "21398578" = "BUCEI-SF.01", "21398598" = "BUCEI-SF.02", "21398588" ="SSMH-BASE","21393049" = "SSMH-SD", "21398599" = "SSMH-SA", "21393044" = "SSMH-SB", "21393049" = "SSMH-SD" , "21206939" = "TNHA-BASE", "21398593" = "TNHA-SA", "21398576"="TNHA-SB","21398601" = "TNHA-SD", "21393047" = "TNHA-SC", "21393048" = "BEO-B06", "21398591" = "BEO-B05"))
dfgrndtemp$depth <- revalue(dfgrndtemp$depth, c("7" = "3.5cm", "8" = "10cm", "9" = "20cm", "10" = "30cm", "11" = "40cm", "12" = "50cm", "13" = "55cm", "14" = "65cm", "15" = "75cm", "16" = "85cm", "17" = "90cm"))
dfgrndtemp$depth = factor(dfgrndtemp$depth, c("3.5cm","10cm", "20cm", "30cm", "40cm", "50cm", "55cm", "65cm", "75cm", "85cm", "90cm"))
```



```{r}
df2 <- dfgrndtemp%>%filter(station=="BUECI",depth=="3.5cm")
ggplot(subset(df2, depth %in% c("3.5cm") & value >.002 | value < -0.002),
       aes(x=Date, y= value, color = sensor)) + 
  geom_miss_point(size = 0.5) +
  guides(color = guide_legend(override.aes = list(size=10))) +
  facet_grid(depth~station) +
  labs(y="Temperature (°C)",color="Station") +
  scale_x_datetime(date_breaks = "1 weeks") +
  scale_y_continuous(breaks=c(-5,-2.5,0,2.5,5,7.5,10,12.5,15), limits=c(-6, 14)) +
  theme(axis.text.x=element_text(angle = 45, hjust = 1.0), axis.line = element_line(colour = "black", size =0.5, linetype = "solid")) +
  theme(plot.title = element_text(hjust = 0.5), 
        plot.caption = element_text(face ="italic")) +
   scale_color_manual(values =c("TNHA-BASE" = "#1B9E77" ,"TNHA-SA" = "#D95F02", "TNHA-SB"="#7570B3", "TNHA-SC" = "#E7298A", "TNHA-SD"="#66A61E","SSMH-BASE"="#807DBA", "SSMH-SA"="#A6761D", "SSMH-SB"= "#4292C6", "SSMH-SC"= "#DD3497", "SSMH-SD"="#7A0177", "BEO-B05"="#6BAED6", "BEO-B06"= "#084594","BUECI-BASE" = "#4E79A7", "BUCEI-SA" = "#F28E2b","BUECI-SB" = "#E15759", "BUCEI-SC" = "#76B7B2", "BUCEI-SD" = "#962D46", "BUCEI-SE" = "#EDC948", "BUCEI-SF.01" = "#9E6BB8" , "BUCEI-SF.02" = "#59A14F"))
```


