---
title: "X-Y_Plots"
author: "Elizabeth Van Metre"
date: '2023-02-10'
output: html_document
---

-------------IMPORTANT FILE PATHS/VALUES-------------

```{r}
filepath = "https://raw.githubusercontent.com/shabanm2/Utqiagvik/main/Meteorological_Seasons_Data/" #Set to prefix of your file location

#Daily Step
datemin = "2022-06-19"
datemax = "2022-09-1"

#Depth of Interest
bestdepth = 8 #8 == 10cm
depthcm = "10 cm"

bestdepthmst = 2 #2 == ??
depthmst = "?? cm"

sensorList = c("TNHA-BASE", "TNHA-SA", "TNHA-SB", "TNHA-SC", "TNHA-SD", "BUCEI-BASE", "BUCEI-SA", "BUCEI-SB", "BUCEI-SC", "BUCEI-SD", "BUCEI-SE", "BUCEI-SF.01", "BUCEI-SF.02", 
                                             "SSMH-BASE", "SSMH-SA", "SSMH-SB", "SSMH-SC", "SSMH-SD")
```


-------------DATA SETUP AND CLEANING-------------

```{r}
library(ggplot2)
library(plyr)
library(dplyr)
library(lubridate)
library(tidyr)
library(gridExtra)
library(forcats)
library(splitstackshape) # basically like text to columns
library(naniar)
library(RColorBrewer)
library(caret)
```

Ground Temperatures for all sites data prepping
```{r}
# importing ground temp data for 6-19 through 9-20
grndtmp=read.csv(paste(filepath,"Summer_grndtmp_2023_04_06_12_21_30_UTC_1.csv",sep = ""))
 
# data cleaning for dataset
names(grndtmp) <- sub("....C..RX3000_BRW1", "", names(grndtmp))
names(grndtmp) <- sub("....C..RX3000_BRW4", "", names(grndtmp))
names(grndtmp) <- sub("....C..RX3000_BRW5", "", names(grndtmp))
names(grndtmp) <- sub("....C..RX3000_BRW6", "", names(grndtmp))
names(grndtmp) <- sub(".RXW.GP6.", "", names(grndtmp))
names(grndtmp) <- sub(".RXW.THC.", "", names(grndtmp))
names(grndtmp) <- sub(".S.THC.", "", names(grndtmp))
names(grndtmp) <- sub("Temperature.", "", names(grndtmp))
grndtmp$Date <-as.POSIXct(grndtmp$Date,format="%m/%d/%y %H:%M",tz="UTC")
#Air Temp Sensor - Remove - NOT ANYMORE (new download good to go)
#grndtmp = grndtmp[,-14]
#THESE ARE BLANK COLUMNS - rewrite if using a different data set
#NOTE: these have gaps in the BEGINNING part of data collection - may not always be blank
#I don't see it in the updated data <3
#grndtmp = grndtmp[,-c(26:36)]
#grndtmp = grndtmp[,-c(92:201)]
raw_ground = grndtmp
```


Ground Moisture for all sites data prepping
```{r}
mst=read.csv(paste(filepath,"Summer_VWC_2023_04_06_12_33_54_UTC_1.csv",sep = ""))

names(mst) <- sub("...m.3.m.3..RX3000_BRW1", "", names(mst))
names(mst) <- sub("...m.3.m.3..RX3000_BRW4", "", names(mst))
names(mst) <- sub("...m.3.m.3..RX3000_BRW5", "", names(mst))
names(mst) <- sub("...m.3.m.3..RX3000_BRW6", "", names(mst))
names(mst) <- sub("..RXW.GP6.", "", names(mst))
names(mst) <- sub("Water.Content", "", names(mst))
mst$Date <-as.POSIXct(mst$Date,format="%m/%d/%y %H:%M",tz="UTC")
```

Solar radiation for all sites data prepping
```{r}
solarrad = read.csv(paste(filepath,"Summer_solar_2023_04_06_13_16_22_UTC_1.csv",sep = ""))

names(solarrad) <- sub("olar.Radiation..RXW.LIB", "" ,names(solarrad))
names(solarrad) <- sub("olar.Radiation..S.LIB", "" ,names(solarrad))
names(solarrad) <- sub("S.", "" ,names(solarrad))
names(solarrad) <- sub("...W.m.2..RX3000_BRW1", "" ,names(solarrad))
names(solarrad) <- sub("...W.m.2..RX3000_BRW4", "" ,names(solarrad))
names(solarrad) <- sub("...W.m.2..RX3000_BRW5", "" ,names(solarrad))
names(solarrad) <- sub("...W.m.2..RX3000_BRW6", "" ,names(solarrad))
solarrad$Date <- as.POSIXct(solarrad$Date,format="%m/%d/%y %H:%M",tz="UTC")
```

#Upload air temp data and clean
```{r}
airtemp =read.csv(paste(filepath,"Summer_airtemp_2023_04_06_11_59_55_UTC_1.csv",sep = ""))

names(airtemp) <- sub("Temperature..RXW.THC.", "" ,names(airtemp))
names(airtemp) <- sub("Temperature..S.THC.", "" ,names(airtemp))
names(airtemp) <- sub("S.", "" ,names(airtemp))
names(airtemp) <- sub("....C..RX3000_BRW1", "" ,names(airtemp))
names(airtemp) <- sub("....C..RX3000_BRW4", "" ,names(airtemp))
names(airtemp) <- sub("....C..RX3000_BRW5", "" ,names(airtemp))
names(airtemp) <- sub("....C..RX3000_BRW6", "" ,names(airtemp))
airtemp$Date <- as.POSIXct(airtemp$Date,format="%m/%d/%y %H:%M",tz="UTC")
```


-------Convert to Long DataFrame-------


#Solar Radiation
```{r fig9, fig.heigt = 14, fig.width = 18}
raw_solar = solarrad

solarrad = gather(raw_solar, variable, response, 3:ncol(raw_solar)) %>%
  filter(!is.na(response)) %>%
  mutate(variable = fct_inorder(variable))

solarrad= cSplit(solarrad, 'variable', sep=".", direction = "wide") # texttocols, 
solarrad$variable_3 <- NULL
colnames(solarrad)[3:5] <- c("value", "station", "sensor")
solarrad$value <- as.numeric(as.character(solarrad$value)) 
solarrad$sensor <- as.factor(as.character(solarrad$sensor))
solarrad$station <- as.factor(solarrad$station)

solarrad$station <- revalue(solarrad$station, c("21198259" = "TNHA", "21401800" = "BUECI", "21401801" = "SSMH", "21401803" = "BEO"))

solarrad$sensor <- revalue(solarrad$sensor, c('21176526'='TNHA-BASE','21362313'='BUECI-SC','21362315'='TNHA-SD','21362316'='BUECI-SD','21362317'='TNHA-SC','21362319'='SSMH-SB','21362320'='BUECI-SE','21390411'='BUECI-BASE','21390413'='SSMH-BASE','21390415'='BEO-BASE','21398616'='TNHA-SB','21398618'='BUECI-SA','21398620'='TNHA-SA','21398622'='SSMH-SA','21398624'='BUECI-SB','21398623'='BUECI-???','21362314'='BUECI-__','21362318'='TNHA-??','21390414'='BUECI-BASE??','21398617'='BUECI-__','21398621'='BUECI-__'))

solarrad <- solarrad %>% filter(!value == -888.88)
```

```{r fig9, fig.heigt = 14, fig.width = 18}

grndtmp = gather(raw_ground, variable, response, 3:ncol(raw_ground)) %>%
  filter(!is.na(response)) %>%
  mutate(variable = fct_inorder(variable))

grndtmp= cSplit(grndtmp, 'variable', sep=".", direction = "wide") # texttocols, 
colnames(grndtmp)[3:6] <- c("value", "station", "sensor","depth")
grndtmp$value <- as.numeric(as.character(grndtmp$value)) 
grndtmp$sensor <- as.factor(as.character(grndtmp$sensor))
grndtmp$station <- as.factor(grndtmp$station)
grndtmp$depth <- as.factor(grndtmp$depth)
grndtmp$station <- revalue(grndtmp$station, c("21198259" = "TNHA", "21401800" = "BUECI", "21401801" = "SSMH", "21401803" = "BEO"))
grndtmp$depth <- revalue(grndtmp$depth, c("7" = "3.5cm", "8" = "10cm", "9" = "20cm", "10" = "30cm", "11"
                                          = "40cm", "12" = "50cm", "13" = "55cm", "14" = "65cm", "15" =
                                            "75cm", "16" = "85cm", "17" = "90cm"))


#Find Sensor Values

grndtmp$sensor <- revalue(grndtmp$sensor, c('21206939'='TNHA-BASE','21393042'='BUECI-SC','21393044'='SSMH-SB','21393047'='TNHA-SC','21393048'='BEO-B05','21393049'='SSMH-SD','21398578'='BUECI-SF01','21398579'='BUECI-SE','21398583'='BUECI-SB','21398584'='BUECI-SD','21398585'='BUECI-BASE','21398588'='SSMH-BASE','21398590'='BUECI-SA','21398591'='BEO-B06','21398593'='TNHA-SA','21398598'='BUECI-SF02','21398599'='SSMH-SA','21398601'='TNHA-SD','21398576'='SSMH-SC','21398587'='TNHA-SB'))

grndtmp <- grndtmp %>% filter(!value == -888.88)
```



```{r fig9, fig.heigt = 14, fig.width = 18}
raw_air = airtemp

airtemp = gather(raw_air, variable, response, 3:ncol(raw_air)) %>%
  mutate(variable = fct_inorder(variable))
airtemp= cSplit(airtemp, 'variable', sep=".", direction = "wide") 
airtemp$variable_3 <- NULL
colnames(airtemp)[3:5] <- c("value", "station", "sensor")
airtemp$value <- as.numeric(as.character(airtemp$value)) 
airtemp$sensor <- as.factor(as.character(airtemp$sensor))
airtemp$station <- as.factor(airtemp$station)
airtemp$station <- revalue(airtemp$station, c("21198259" = "TNHA", "21401800" = "BUECI", "21401801" = "SSMH", "21401803" = "BEO")) 
airtemp$sensor <- revalue(airtemp$sensor, c('21187245'='BUECI-SE','21218018'='TNHA-BASE','21362254'='BUECI-SB','21362256'='BUECI-SD','21380919'='TNHA-SA','21390849'='SSMH-BASE','21390851'='BUECI-BASE','21397541'='BEO-BASE','21398665'='SSMH-SB','21398666'='TNHA-SD','21398668'='BUECI-SC','21398670'='SSMH-SA','21398671'='BUECI-SA','21398674'='TNHA-SC','21398676'='TNHA-SB','21397542'='BUECI-BASE??','21398659'='BUECI-__','21398661'='BUECI-__','21398664'='TNHA-??'))
#TNHA-A and TNHA-B are GUESSES - need metadata on ground

airtemp <- airtemp %>% filter(!value == -888.88)

```

```{r fig9, fig.heigt = 14, fig.width = 18}
grndmst = mst

grndmst = gather(grndmst, variable, response, 3:ncol(grndmst)) %>%
  filter(!is.na(response)) %>%
  mutate(variable = fct_inorder(variable))

grndmst= cSplit(grndmst, 'variable', sep=".", direction = "wide") # texttocols, 
colnames(grndmst)[3:6] <- c("value", "station", "sensor","depth")
grndmst$value <- as.numeric(as.character(grndmst$value)) 
grndmst$sensor <- as.factor(as.character(grndmst$sensor))
grndmst$station <- as.factor(grndmst$station)

grndmst$station <- revalue(grndmst$station, c("21198259" = "TNHA", "21401800" = "BUCEI", "21401801" = "SSMH", "21401803" = "BEO"))



#Find Sensor Values

grndmst$sensor <- revalue(grndmst$sensor, c('21206939'='TNHA-BASE','21393042'='BUECI-SC','21393044'='SSMH-SB','21393047'='TNHA-SC','21393048'='BEO-BASE','21393049'='SSMH-SD','21398578'='BUECI-SF01','21398579'='BUECI-SE','21398583'='BUECI-SB','21398584'='BUECI-SD','21398585'='BUECI-BASE','21398588'='SSMH-BASE','21398590'='BUECI-SA','21398591'='BEO-BASE','21398593'='TNHA-SA','21398598'='BUECI-SF02','21398599'='SSMH-SA','21398601'='TNHA-SD','21398576'='REMOVE','21398587'='TNHA-SB'						))

grndmst <- grndmst %>% filter(!value == -888.88)

```

-------Convert to Daily Values-------

```{r}
avgdailysolar = data.frame(Date=NA, value=NA, station=NA, sensor=NA)[numeric(0), ]


for(sensorName in sensorList){
  
  if(any(solarrad$sensor==sensorName)){
    daily = solarrad %>% filter(sensor==sensorName) %>% filter(as.Date(Date, "%Y-%m-%d") <= datemax) %>%                 filter(as.Date(Date, "%Y-%m-%d") >= datemin)

    daily$Date = floor_date(daily$Date, unit = "days", week_start = getOption("lubridate.week.start",7))

    daily = aggregate(value ~ Date, daily, mean, na.rm=T)
    sensor = rep(sensorName, nrow(daily))
    station = rep(sub(c("-BASE|-SA|-SB|-SC|-SD|-SE|-SF.01|-SF.02"), "" ,sensorName), nrow(daily))
    daily = data.frame(daily, station, sensor)
    avgdailysolar = rbind(avgdailysolar, daily)
  }
}

colnames(avgdailysolar)[2] = "solar"

```

```{r}
avgdailyground = data.frame(Date=NA, value=NA, station=NA, sensor=NA)[numeric(0), ]


for(sensorName in sensorList){
  #Make sure sensor has data - otherwise will throw error
    if(any(solarrad$sensor==sensorName)){
      daily = grndtmp %>% filter(sensor==sensorName) %>% filter(depth == bestdepth) %>% 
        filter(as.Date(Date, "%Y-%m-%d") <= datemax) %>% filter(as.Date(Date, "%Y-%m-%d") >= datemin)
      if(nrow(daily) > 0){
          daily$Date = floor_date(daily$Date, unit = "days", week_start = getOption("lubridate.week.start",      7))

        daily = aggregate(value ~ Date, daily, mean, na.rm=T)
        sensor = rep(sensorName, nrow(daily))
        station = rep(sub(c("-BASE|-SA|-SB|-SC|-SD|-SE|-SF.01|-SF.02"), "" ,sensorName), nrow(daily))
        daily = data.frame(daily, station, sensor)
        avgdailyground = rbind(avgdailyground, daily)
      }
    }

  
}

colnames(avgdailyground)[2] = "grndtmp"

```

```{r}
avgdailymst = data.frame(Date=NA, value=NA, station=NA, sensor=NA)[numeric(0), ]


for(sensorName in sensorList){
  #Make sure sensor has data - otherwise will throw error
    
    daily = grndmst %>% filter(sensor==sensorName) %>% filter(depth == bestdepthmst) %>% filter(as.Date(Date, "%Y-%m-%d") <= datemax) %>%                 filter(as.Date(Date, "%Y-%m-%d") >= datemin)
if(nrow(daily) > 0){
  daily$Date = floor_date(daily$Date, unit = "days", week_start = getOption("lubridate.week.start",      7))

  daily = aggregate(value ~ Date, daily, mean, na.rm=T)
  sensor = rep(sensorName, nrow(daily))
  station = rep(sub(c("-BASE|-SA|-SB|-SC|-SD|-SE|-SF.01|-SF.02"), "" ,sensorName), nrow(daily))
  daily = data.frame(daily, station, sensor)
  avgdailymst = rbind(avgdailymst, daily)
}

  
}

colnames(avgdailymst)[2] = "moisture"

```

-------Merge Data Frames-------

```{r}
averages = avgdailysolar %>% full_join(avgdailyground, by=c("Date","sensor","station")) %>% 
  full_join(avgdailymst, by=c("Date","sensor","station")) 
solar = averages[,2]
averages = averages[,-2]
averages = data.frame(averages, solar)
```

-------Graphs-------

```{r}
model = train(grndtmp~solar, averages, method="lm", na.action = na.exclude)
summary(model)

pred <- predict(model, averages, na.action = na.pass)

averages = data.frame(averages, pred)

```

```{r}
mstmodel = train(grndtmp~moisture, averages, method="lm", na.action = na.exclude)
mstpred = predict(mstmodel, averages, na.action = na.pass)

averages = data.frame(averages, mstpred)

summary(mstmodel)
```


```{r}
averages$sensor = sub(c("TNHA-|SSMH-|BUCEI-|BEO-"), "" ,averages$sensor)
```


#Solar Radiation and GT
```{r fig8, fig.height = 9, fig.width = 16}
ymax = round(max(averages$grndtmp, na.rm = TRUE),-1) + 2.5
ymin = round_any(min(averages$grndtmp, na.rm = TRUE),10, f=floor)
xmax = round(max(averages$solar, na.rm = TRUE),-2)
xmin = round_any(min(averages$solar, na.rm = TRUE),100, f=floor)-40

ggplot() +
  geom_point(data=averages, aes(x=solar, y=grndtmp, color = station, shape = sensor), size = 5) +
  
  geom_line(data=averages, aes(x=solar, y=pred, color="Regression Line"), size=1) +
  
  

  theme_bw() +
  labs(title= paste("Ground Temperature v. Solar Radiation (",datemin,"to",datemax,"at",depthcm,")"), x="Solar Radiation (W/"~m^2~")", y="Ground Temperature (°C)",color="Station") + 
  #scale_x_datetime(breaks = datestep, minor_breaks = dateminstep) +
  
  stat_summary(fun.data= mean_cl_normal) + 
  geom_smooth(method='lm', formula = y ~ x, na.rm = TRUE) +
  
  theme(axis.text.y =element_text(face="bold",size=20,family="Times New Roman"),
        axis.text.x=element_text(face = "bold",size = 20,family="Times New Roman"), 
        axis.line = element_line(colour = "black", size =0.5, linetype = "solid")) +
  theme(axis.title.x = element_text(size=32,family="Times New Roman"), 
        axis.title.y = element_text(size=32,family="Times New Roman"), 
        legend.text = element_text(size=32,family="Times New Roman"), 
        legend.title = element_text(size=38,face="bold",family="Times New Roman")) +
  
  theme(plot.title = element_text(hjust = 0.5,size=46,family="Times New Roman"), 
        plot.caption = element_text(face ="italic")) +
  scale_y_continuous(limits=c(ymin, ymax), minor_breaks = seq(ymin, ymax+1, by = 0.25)) +
  scale_x_continuous(limits=c(xmin, xmax), minor_breaks = seq(xmin, xmax+20, by = 10)) +
  scale_colour_hue() +
  
  annotate("rect", xmin = xmin, xmax = xmin+100, ymin = ymax-3.5, ymax = ymax,
  alpha = .8, fill = "black") +
  annotate("rect", xmin = xmin+2, xmax = xmin+98, ymin = ymax-3.4, ymax = ymax-0.1,
  alpha = 1, fill = "lightgray") +
  annotate("text", x = xmin+50, y = (ymax-1.7), label = paste("Simple Linear Regression",
                                                  "\ny =",round(model$finalModel$coefficients[1],2),"+",
                                                  round(model$finalModel$coefficients[2],4),"(x)",
                                                  "\nR-Squared =",round(model$results$Rsquared,4),
                                                  "\nRMSE =",round(model$results$RMSE,4),
                                                  "\nF-Statistic =",round(summary(model)$fstatistic[1],4),"df =",
                                                  round(summary(model)$fstatistic[2]), ",", round(summary(model)$fstatistic[3]),
                                                  "\np-value =",round(pf(summary(model)$fstatistic[1], summary(model)$fstatistic[2],
                                                                   summary(model)$fstatistic[3], lower.tail = FALSE)),4),
           size=11, family="Times New Roman")+
  scale_shape_manual(values = c(19,15,17,18,16,20,1,2))
  

```


***********CURRENTLY NOT WORKING -- NEED TO UPDATE WITH ABOVE GGPLOT CODE***********

#Ground Moisture and GT
```{r fig8, fig.height = 9, fig.width = 16}
ymax = round(max(averages$grndtmp, na.rm = TRUE),-1) + 2.5
ymin = round_any(min(averages$grndtmp, na.rm = TRUE),10, f=floor)
xmax = round(max(averages$moisture, na.rm = TRUE),2)
xmin = round_any(min(averages$moisture, na.rm = TRUE),2, f=floor)-0.05

ggplot() +
  geom_point(data=averages, aes(x=moisture, y=grndtmp, color = sensor), size = 5) +
  
  geom_line(data=averages, aes(x=moisture, y=mstpred, color="red"), size=1) +
  
  

  theme_bw() +
  labs(title= paste("Ground Temperature v. Ground Moisture (",datemin,"to",datemax,"at",depthmst,")"), x="Volumetric Water Content ("~m^3~"/"~m^3~")", y="Ground Temperature (°C)",color="Station") + 
  #scale_x_datetime(breaks = datestep, minor_breaks = dateminstep) +
  
  stat_summary(fun.data= mean_cl_normal) + 
  geom_smooth(method='lm', formula = y ~ x, na.rm = TRUE) +
  
  theme(axis.text.y =element_text(face="bold",size=20,family="Times New Roman"),
        axis.text.x=element_text(face = "bold",size = 20,family="Times New Roman"), 
        axis.line = element_line(colour = "black", size =0.5, linetype = "solid")) +
  theme(axis.title.x = element_text(size=32,family="Times New Roman"), 
        axis.title.y = element_text(size=32,family="Times New Roman"), 
        legend.text = element_text(size=32,family="Times New Roman"), 
        legend.title = element_text(size=38,face="bold",family="Times New Roman")) +
  
  theme(plot.title = element_text(hjust = 0.5,size=46,family="Times New Roman"), 
        plot.caption = element_text(face ="italic")) +
  scale_y_continuous(limits=c(ymin, ymax), minor_breaks = seq(ymin, ymax+1, by = 0.25)) +
  scale_x_continuous(limits=c(xmin, xmax), minor_breaks = seq(xmin, xmax+0.1, by = 0.02)) +
  scale_colour_hue(breaks=sensorList) +
  
  annotate("rect", xmin = xmin, xmax = xmin+0.15, ymin = ymax-3.5, ymax = ymax,
  alpha = .8, fill = "black") +
  annotate("rect", xmin = xmin+0.003, xmax = xmin+0.147, ymin = ymax-3.4, ymax = ymax-0.1,
  alpha = 1, fill = "lightgray") +
  annotate("text", x = xmin+0.072, y = (ymax-1.7), label = paste("Simple Linear Regression",
                                                  "\ny =",round(mstmodel$finalModel$coefficients[1],2),"+",
                                                  round(mstmodel$finalModel$coefficients[2],4),"(x)",
                                                  "\nR-Squared =",round(mstmodel$results$Rsquared,4),
                                                  "\nRMSE =",round(mstmodel$results$RMSE,4),
                                                  "\nF-Statistic =",round(summary(mstmodel)$fstatistic[1],4),"df =",
                                                  round(summary(mstmodel)$fstatistic[2]), ",", round(summary(mstmodel)$fstatistic[3]),
                                                  "\np-value =",round(pf(summary(mstmodel)$fstatistic[1], summary(mstmodel)$fstatistic[2],
                                                                   summary(mstmodel)$fstatistic[3], lower.tail = FALSE),4)),
           size=11, family="Times New Roman")
  

```
