---
title: "X-Y_Plots"
authors: "Elizabeth Van Metre, Mirella Shaban"
date: '2023-02-10'
output: html_document
---

-------------IMPORTANT FILE PATHS/VALUES-------------

```{r}
filepath = "~/Desktop/Arctic/" #Set to prefix of your file location

#Daily Step
datemin = "2022-06-19"
datemax = "2022-09-19"

#Depth of Interest
bestdepth = 8 #8 == 10cm
depthcm = "10 cm"
```


-------------DATA SETUP AND CLEANING-------------

```{r}

library(ggplot2)
library(plyr)
library(dplyr)
library(lubridate)
library(tidyr)
library(gridExtra)
library(forcats)
library(splitstackshape) # basically like text to columns
library(naniar)
library(RColorBrewer)
library(caret)
```

Ground Temperatures for all sites data prepping
```{r}
# importing ground temp data for 6-19 through 9-20
grndtmp=read.csv(paste(filepath,"Season_GRNDTMP_6_19_22_9_20_22_2022_09_21_16_19_26_UTC_1.csv",sep = ""))
 
# data cleaning for dataset
names(grndtmp) <- sub("....C..RX3000_BRW1", "", names(grndtmp))
names(grndtmp) <- sub("....C..RX3000_BRW4", "", names(grndtmp))
names(grndtmp) <- sub("....C..RX3000_BRW5", "", names(grndtmp))
names(grndtmp) <- sub("....C..RX3000_BRW6", "", names(grndtmp))
names(grndtmp) <- sub(".RXW.GP6.", "", names(grndtmp))
names(grndtmp) <- sub("Temperature.", "", names(grndtmp))
grndtmp$Date <-as.POSIXct(grndtmp$Date,format="%m/%d/%y %H:%M",tz="UTC")
#Air Temp Sensor - Remove
grndtmp = grndtmp[,-14]
#THESE ARE BLANK COLUMNS - rewrite if using a different data set
#NOTE: these have gaps in the BEGINNING part of data collection - may not always be blank
grndtmp = grndtmp[,-c(26:36)]
grndtmp = grndtmp[,-c(92:201)]
raw_ground = grndtmp
```


Ground Moisture for all sites data prepping
```{r}
mst=read.csv(paste(filepath,"Season_VWC_6_19_22_9_20_22_2022_09_21_16_11_28_UTC_1.csv",sep = ""))

names(mst) <- sub("...m.3.m.3..RX3000_BRW1", "", names(mst))
names(mst) <- sub("...m.3.m.3..RX3000_BRW4", "", names(mst))
names(mst) <- sub("...m.3.m.3..RX3000_BRW5", "", names(mst))
names(mst) <- sub("...m.3.m.3..RX3000_BRW6", "", names(mst))
names(mst) <- sub("..RXW.GP6.", "", names(mst))
mst$Date <-as.POSIXct(mst$Date,format="%m/%d/%y %H:%M",tz="UTC")
```

Solar radiation for all sites data prepping
```{r}
solarrad = read.csv(paste(filepath,"Season_SOLARAD_6_19_22_9_20_22_2022_09_21_16_27_20_UTC_1.csv",sep = ""))

names(solarrad) <- sub("olar.Radiation..RXW.LIB", "" ,names(solarrad))
names(solarrad) <- sub("olar.Radiation..S.LIB", "" ,names(solarrad))
names(solarrad) <- sub("S.", "" ,names(solarrad))
names(solarrad) <- sub("...W.m.2..RX3000_BRW1", "" ,names(solarrad))
names(solarrad) <- sub("...W.m.2..RX3000_BRW4", "" ,names(solarrad))
names(solarrad) <- sub("...W.m.2..RX3000_BRW5", "" ,names(solarrad))
names(solarrad) <- sub("...W.m.2..RX3000_BRW6", "" ,names(solarrad))
solarrad$Date <- as.POSIXct(solarrad$Date,format="%m/%d/%y %H:%M",tz="UTC")
```

#Upload air temp data and clean
```{r}
airtemp =read.csv(paste(filepath,"Season_AIRTMP_6_19_22_9_20_22_2022_09_21_16_21_48_UTC_1.csv",sep = ""))

names(airtemp) <- sub("Temperature..RXW.THC.", "" ,names(airtemp))
names(airtemp) <- sub("Temperature..S.THC.", "" ,names(airtemp))
names(airtemp) <- sub("S.", "" ,names(airtemp))
names(airtemp) <- sub("....C..RX3000_BRW1", "" ,names(airtemp))
names(airtemp) <- sub("....C..RX3000_BRW4", "" ,names(airtemp))
names(airtemp) <- sub("....C..RX3000_BRW5", "" ,names(airtemp))
names(airtemp) <- sub("....C..RX3000_BRW6", "" ,names(airtemp))
airtemp$Date <- as.POSIXct(airtemp$Date,format="%m/%d/%y %H:%M",tz="UTC")
```


-------Convert to Long DataFrame-------

#Solar Radiation
```{r fig9, fig.heigt = 14, fig.width = 18}
raw_solar = solarrad

solarrad = gather(solarrad, variable, response, '21401801.21362319.1':'21198259.21398620.1') %>%
  filter(!is.na(response)) %>%
  mutate(variable = fct_inorder(variable))

solarrad= cSplit(solarrad, 'variable', sep=".", direction = "wide") # texttocols, 
solarrad$variable_3 <- NULL
colnames(solarrad)[3:5] <- c("value", "station", "sensor")
solarrad$value <- as.numeric(as.character(solarrad$value)) 
solarrad$sensor <- as.factor(as.character(solarrad$sensor))
solarrad$station <- as.factor(solarrad$station)

solarrad$station <- revalue(solarrad$station, c("21198259" = "TNHA", "21401800" = "BUECI", "21401801" = "SSMH", "21401803" = "BEO"))





solarrad$sensor <- revalue(solarrad$sensor, c("21390411" = "BUECI-BASE", "21398618" = "BUCEI-SA", "21398624" = "BUECI-SB", "21362313" = "BUCEI-SC", "21362316" = "BUCEI-SD", "21362320" = "BUCEI-SE", "21398578" = "BUCEI-SF.01", "21398598" = "BUCEI-SF.02", 
                                              "21390413" ="SSMH-BASE", "21398622" = "SSMH-SA", "21362319" = "SSMH-SB", "21166008" = "SSMH-SC", "21393049" = "SSMH-SD" ,
                                              "21176526" = "TNHA-BASE", "21398620" = "TNHA-SA", "21398616"="TNHA-SB","21362315" = "TNHA-SD", "21362317" = "TNHA-SC", 
                                              "21390415" = "BEO-Base"))

solarrad <- solarrad %>% filter(!value == -888.88)
```

```{r fig9, fig.heigt = 14, fig.width = 18}
grndtmp = raw_ground

grndtmp = gather(grndtmp, variable, response, 3:ncol(grndtmp)) %>%
  filter(!is.na(response)) %>%
  mutate(variable = fct_inorder(variable))

grndtmp= cSplit(grndtmp, 'variable', sep=".", direction = "wide") # texttocols, 
colnames(grndtmp)[3:6] <- c("value", "station", "sensor","depth")
grndtmp$value <- as.numeric(as.character(grndtmp$value)) 
grndtmp$sensor <- as.factor(as.character(grndtmp$sensor))
grndtmp$station <- as.factor(grndtmp$station)
grndtmp$depth <- as.factor(grndtmp$depth)
grndtmp$station <- revalue(grndtmp$station, c("21198259" = "TNHA", "21401800" = "BUECI", "21401801" = "SSMH", "21401803" = "BEO"))
grndtmp$depth <- revalue(grndtmp$depth, c("7" = "3.5cm", "8" = "10cm", "9" = "20cm", "10" = "30cm", "11"
                                          = "40cm", "12" = "50cm", "13" = "55cm", "14" = "65cm", "15" =
                                            "75cm", "16" = "85cm", "17" = "90cm"))


#Find Sensor Values

grndtmp$sensor <- revalue(grndtmp$sensor, c("21398585" = "BUECI-BASE", "21398590" = "BUCEI-SA", "21398583" = "BUECI-SB", "21393042" = "BUCEI-SC", "21398584" = "BUCEI-SD", "21398579" = "BUCEI-SE", "21398578" = "BUCEI-SF.01", "21398598" = "BUCEI-SF.02", "21398588" ="SSMH-BASE","21393049" = "SSMH-SD", "21398599" = "SSMH-SA", "21393044" = "SSMH-SB", "21393049" = "SSMH-SD" , "21206939" = "TNHA-BASE", "21398593" = "TNHA-SA", "21398576"="TNHA-SB","21398601" = "TNHA-SD", "21393047" = "TNHA-SC", "21393048" = "BEO-B06", "21398591" = "BEO-B05"))

grndtmp <- grndtmp %>% filter(!value == -888.88)
```



```{r fig9, fig.heigt = 14, fig.width = 18}
raw_air = airtemp

airtemp = gather(airtemp, variable, response, "21198259.21380919.1":"21401803.21397541.1") %>%
  mutate(variable = fct_inorder(variable))
airtemp= cSplit(airtemp, 'variable', sep=".", direction = "wide") 
airtemp$variable_3 <- NULL
colnames(airtemp)[3:5] <- c("value", "station", "sensor")
airtemp$value <- as.numeric(as.character(airtemp$value)) 
airtemp$sensor <- as.factor(as.character(airtemp$sensor))
airtemp$station <- as.factor(airtemp$station)
airtemp$station <- revalue(airtemp$station, c("21198259" = "TNHA", "21401800" = "BUECI", "21401801" = "SSMH", "21401803" = "BEO")) 
airtemp$sensor <- revalue(airtemp$sensor, c("21390851" = "BUECI-BASE", "21398671" = "BUCEI-SA", "21362254" = "BUECI-SB", "21398668" = "BUCEI-SC", "21398660" = "BUCEI-SD", "21187245" = "BUCEI-SE",
                                            "21390849" ="SSMH-BASE","21393049" = "SSMH-SD", "21398670" = "SSMH-SA", "21398665" = "SSMH-SB",
                                            "21218018" = "TNHA-BASE", "21380919" = "TNHA-SA" , "21398676"="TNHA-SB","21398666" = "TNHA-SD", "21398674" = "TNHA-SC", "21397541" = "BEO-BASE"))
#TNHA-A and TNHA-B are GUESSES - need metadata on ground

airtemp <- airtemp %>% filter(!value == -888.88)

```
-------Convert to Daily Values-------

```{r}
avgdailysolar_TNHA = data.frame(Date=NA, value=NA, station=NA, sensor=NA)[numeric(0), ]
sensorList = c("TNHA-BASE", "TNHA-SA", "TNHA-SB", "TNHA-SC", "TNHA-SD")


for(sensorName in sensorList){
  daily = solarrad %>% filter(sensor==sensorName) %>% filter(as.Date(Date, "%Y-%m-%d") <= datemax) %>%                 filter(as.Date(Date, "%Y-%m-%d") >= datemin)

  daily$Date = floor_date(daily$Date, unit = "days", week_start = getOption("lubridate.week.start",      7))
           
  daily = aggregate(value ~ Date, daily, mean, na.rm=T)
  sensor = rep(sensorName, nrow(daily))
  station = rep(sub(c("-BASE|-SA|-SB|-SC|-SD"), "" ,sensorName), nrow(daily))
  daily = data.frame(daily, station, sensor)
  avgdailysolar_TNHA = rbind(avgdailysolar_TNHA, daily)
}

colnames(avgdailysolar_TNHA)[2] = "solar"

```

```{r}
#grndtmp_10cm <- grndtmp %>% filter(depth == "10cm")
avgdailyground_TNHA = data.frame(Date=NA, value=NA, station=NA, sensor=NA)[numeric(0), ]
sensorList = c("TNHA-BASE", "TNHA-SA", "TNHA-SC", "TNHA-SD")


for(sensorName in sensorList){
  #Make sure sensor has data - otherwise will throw error
    
    daily = grndtmp %>% filter(sensor==sensorName) %>% filter(as.Date(Date, "%Y-%m-%d") <= datemax) %>%
      filter(as.Date(Date, "%Y-%m-%d") >= datemin)
if(nrow(daily) > 0){
  daily$Date = floor_date(daily$Date, unit = "days", week_start = getOption("lubridate.week.start",      7))

  daily = aggregate(value ~ Date, daily, mean, na.rm=T)
  sensor = rep(sensorName, nrow(daily))
  station = rep(sub(c("-BASE|-SA|-SC|-SD"), "" ,sensorName), nrow(daily))
  daily = data.frame(daily, station, sensor)
  grndtmp_10cm = rbind(grndtmp_10cm, daily)
}

  
}

colnames(avgdailyground_TNHA)[2] = "grndtmp"
# i dont believe this chunk works ----> currently NOT VITAL TO THE SCRIPT.
```

```{r}
avgdailyair_TNHA = data.frame(Date=NA, value=NA, station=NA, sensor=NA)[numeric(0), ]
sensorList = c("TNHA-BASE", "TNHA-SA", "TNHA-SB", "TNHA-SC", "TNHA-SD")


for(sensorName in sensorList){
  daily = airtemp %>% filter(sensor==sensorName) %>% filter(as.Date(Date, "%Y-%m-%d") <= datemax) %>%                 filter(as.Date(Date, "%Y-%m-%d") >= datemin)

  daily$Date = floor_date(daily$Date, unit = "days", week_start = getOption("lubridate.week.start",      7))

  daily = aggregate(value ~ Date, daily, mean, na.rm=T)
  sensor = rep(sensorName, nrow(daily))
  station = rep(sub(c("-BASE|-SA|-SB|-SC|-SD"), "" ,sensorName), nrow(daily))
  daily = data.frame(daily, station, sensor)
  avgdailyair_TNHA= rbind(avgdailyair_TNHA, daily)
}

colnames(avgdailyair_TNHA)[2] = "airtemp"
```

----- AMPLITUDE -----

```{r}
grndamp <- grndtmp %>% filter(grndtmp$depth == "10cm", !value == 0.0) 
grndamp <- grndamp %>%
  group_by(Date) %>%
  mutate(
    Max_grnd = max(value, na.rm = T),
    Min_grnd = min(value, na.rm = T),
    mean_grnd = mean(value, na.rm = T),
    amplitude = (Max_grnd-Min_grnd)
  ) %>%
   arrange(sensor)

grndamp$Date <- as.Date(grndamp_clean$Date)

grndamp_averages <- grndamp %>% group_by(Date, sensor, Date = as.Date(Date)) %>% summarise(across(c(Max_grnd, Min_grnd, mean_grnd, amplitude), mean))

#grndamp2 <- grndamp %>% tidyr::pivot_wider(id_cols = Date, names_from = sensor, values_from = amplitude, values_fn = function(x) mean(x, na.rm = T))

#grndamp2 does the same as grndamp1 but as a wide dataframe !!!!


# consider using xts for apply.weekly, apply.mothly etc. actions to aggregate data over time
```

-------Merge Data Frames-------

```{r}
averages = avgdailysolar_TNHA %>% full_join(avgdailyground_TNHA, by=c("Date","sensor","station"))
solar = averages[,2]
averages = averages[,-2]
averages = data.frame(averages, solar)

averages = averages %>% full_join(avgdailyair_TNHA, by=c("Date","sensor","station"))
averages = averages %>% full_join(grndamp_averages, by=c("Date", "sensor"))
```

-------Graphs for One Week-------

```{r}
model = train(solar~airtemp, averages, method="lm", na.action = na.exclude)
summary(model)

pred <- predict(model, averages)

averages = data.frame(averages, pred)

#one week time span
```

```{r}
model1 = train(grndtmp~airtemp, averages, method="lm", na.action = na.exclude)
summary(model1)
pred1 <- predict(model1,averages)
head(pred)
averages = data.frame(averages,pred1)
```


NOTE: currently displayed as points --> form linear regression?

```{r fig8, fig.height = 9, fig.width = 16}
ymax = round(max(averages$grndtmp, na.rm = TRUE),-1) + 2.5
ymin = round_any(min(averages$grndtmp, na.rm = TRUE),10, f=floor)
xmax = round(max(averages$solar, na.rm = TRUE),-2)
xmin = round_any(min(averages$solar, na.rm = TRUE),100, f=floor)-40

ggplot() +
  geom_point(data=averages, aes(x=solar, y=grndtmp, color = sensor), size = 5) +
  
  geom_line(data=averages, aes(x=solar, y=pred, color="red"), size=1) +
  
  

  theme_bw() +
  labs(title= paste("Ground Temperature v. Solar Radiation (",datemin,"to",datemax,"at",depthcm,")"), x="Solar Radiation (W/"~m^2~")", y="Ground Temperature (°C) @ 10cm ",color="Station") + 
  #scale_x_datetime(breaks = datestep, minor_breaks = dateminstep) +
  
  stat_summary(fun.data= mean_cl_normal) + 
  geom_smooth(method='lm', formula = y ~ x, na.rm = TRUE) +
  
  theme(axis.text.y =element_text(face="bold",size=20,family="Times New Roman"),
        axis.text.x=element_text(face = "bold",size = 20,family="Times New Roman"), 
        axis.line = element_line(colour = "black", size =0.5, linetype = "solid")) +
  theme(axis.title.x = element_text(size=32,family="Times New Roman"), 
        axis.title.y = element_text(size=32,family="Times New Roman"), 
        legend.text = element_text(size=32,family="Times New Roman"), 
        legend.title = element_text(size=38,face="bold",family="Times New Roman")) +
  
  theme(plot.title = element_text(hjust = 0.5,size=46,family="Times New Roman"), 
        plot.caption = element_text(face ="italic")) +
  scale_y_continuous(limits=c(ymin, ymax), minor_breaks = seq(0, ymax+1, by = 0.25)) +
  scale_x_continuous(limits=c(xmin, xmax), minor_breaks = seq(-20, xmax+20, by = 10)) +
  scale_colour_hue(breaks=c("TNHA-BASE","TNHA-SA", "TNHA-SC", "TNHA-SD")) +
  
  annotate("rect", xmin = xmin, xmax = xmin+100, ymin = ymax-3.5, ymax = ymax,
  alpha = .8, fill = "black") +
  annotate("rect", xmin = xmin+2, xmax = xmin+98, ymin = ymax-3.4, ymax = ymax-0.1,
  alpha = 1, fill = "lightgray") +
  annotate("text", x = xmin+50, y = (ymax-1.7), label = paste("Simple Linear Regression",
                                                  "\ny =",round(model$finalModel$coefficients[1],2),"+",
                                                  round(model$finalModel$coefficients[2],4),"(x)",
                                                  "\nR-Squared =",round(model$results$Rsquared,4),
                                                  "\nRMSE =",round(model$results$RMSE,4),
                                                  "\nF-Statistic =",round(summary(model)$fstatistic[1],4),"df =",
                                                  round(summary(model)$fstatistic[2]), ",", round(summary(model)$fstatistic[3]),
                                                  "\np-value =",pf(summary(model)$fstatistic[1], summary(model)$fstatistic[2],
                                                                   summary(model)$fstatistic[3], lower.tail = FALSE)),
           size=11, family="Times New Roman")
  

```
# Are we testing each sensors ground temp vs its own solar rad? (ABOVE-- yes we are)
```{r fig8, fig.height = 9, fig.width = 16}
ymax = round(max(averages$grndtmp, na.rm = TRUE),-1) + 2.5
ymin = round_any(min(averages$grndtmp, na.rm = TRUE),10, f=floor)
xmax = round(max(averages$airtemp, na.rm = TRUE),-2)
xmin = round_any(min(averages$airtemp, na.rm = TRUE),100, f=floor)-40

ggplot() +
  geom_point(data=averages, aes(x=airtemp, y=grndtmp, color = sensor), size = 5) +
  
  geom_line(data=averages, aes(x=airtemp, y=pred, color="red"), size=1) +
  
  

  theme_bw() +
  labs(title= paste("Ground Temperature v. Solar Radiation (",datemin,"to",datemax,"at",depthcm,")"), x="Air Temperature", y="Ground Temperature (°C) @ 10cm",color="Station") + 
  #scale_x_datetime(breaks = datestep, minor_breaks = dateminstep) +
  
  stat_summary(fun.data= mean_cl_normal) + 
  geom_smooth(method='lm', formula = y ~ x, na.rm = TRUE) +
  
  theme(axis.text.y =element_text(face="bold",size=20,family="Times New Roman"),
        axis.text.x=element_text(face = "bold",size = 20,family="Times New Roman"), 
        axis.line = element_line(colour = "black", size =0.5, linetype = "solid")) +
  theme(axis.title.x = element_text(size=32,family="Times New Roman"), 
        axis.title.y = element_text(size=32,family="Times New Roman"), 
        legend.text = element_text(size=32,family="Times New Roman"), 
        legend.title = element_text(size=38,face="bold",family="Times New Roman")) +
  
  theme(plot.title = element_text(hjust = 0.5,size=46,family="Times New Roman"), 
        plot.caption = element_text(face ="italic")) +
  scale_y_continuous(limits=c(ymin, ymax), minor_breaks = seq(0, ymax+1, by = 0.25)) +
  scale_x_continuous(limits=c(xmin, xmax), minor_breaks = seq(-20, xmax+20, by = 10)) +
  scale_colour_hue(breaks=c("TNHA-BASE","TNHA-SA", "TNHA-SC", "TNHA-SD")) +
  
  annotate("rect", xmin = xmin, xmax = xmin+100, ymin = ymax-3.5, ymax = ymax,
  alpha = .8, fill = "black") +
  annotate("rect", xmin = xmin+2, xmax = xmin+98, ymin = ymax-3.4, ymax = ymax-0.1,
  alpha = 1, fill = "lightgray") +
  annotate("text", x = xmin+50, y = (ymax-1.7), label = paste("Simple Linear Regression",
                                                  "\ny =",round(model$finalModel$coefficients[1],2),"+",
                                                  round(model$finalModel$coefficients[2],4),"(x)",
                                                  "\nR-Squared =",round(model$results$Rsquared,4),
                                                  "\nRMSE =",round(model$results$RMSE,4),
                                                  "\nF-Statistic =",round(summary(model)$fstatistic[1],4),"df =",
                                                  round(summary(model)$fstatistic[2]), ",", round(summary(model)$fstatistic[3]),
                                                  "\np-value =",pf(summary(model)$fstatistic[1], summary(model)$fstatistic[2],
                                                                   summary(model)$fstatistic[3], lower.tail = FALSE)),
           size=11, family="Times New Roman")
  


```

# Plotting XY figures of stations grnd tmp vs air tmp against eachother for later gap filling comparisons

```{r}
XY_grnd_air= averages %>% filter(!sensor == "TNHA-BASE", !sensor == "TNHA-SA", !sensor == "TNHA-SB") 
  ggplot(data = XY_grnd_air, aes(x=airtemp, y = grndtmp, color=sensor)) +
  geom_point()+
  theme_bw() + 
    labs(title= "TNHA-SC vs. TNHA-SD @ 10cm depth, 6/19/22-9/19/22", x = "Air Temperature", y="Ground Temperature (°C) @ 10cm",color="Station") + 
  theme(axis.text.y = element_text(size = 15)) +
  theme(axis.text.x=element_text(angle = 45, hjust = 1.0, size = 15), 
        axis.line = element_line(colour = "black", size =0.5, 
                                 linetype = "solid")) +
  theme(strip.text.y = element_text(size = 15),plot.title = element_text(hjust = 0.5, size = 20), 
        plot.caption = element_text(face ="italic"),
        strip.text = element_text(size = 15),
        axis.title = element_text(size = 15)) +
  theme(axis.title.y = element_text(margin = margin(r=15))) +
  theme(axis.title.x = element_text(margin = margin(t=15))) +
  theme(legend.title = element_text(size = 15),
        legend.text = element_text(size = 10),
        legend.key.height = unit(1,'cm')) +
    geom_smooth(method=lm, se=TRUE)  #add a line of best fit
  
  #add date min and max
```
#


```{r}
XY_grnd_air = averages %>% filter(!sensor == "TNHA-SC", !sensor == "TNHA-SD", !sensor == "TNHA-SB") 
  ggplot(data = XY_grnd_air, aes(x=airtemp, y = grndtmp, color=sensor)) +
  geom_point()+
  theme_bw() + 
    labs(title= "TNHA-BASE vs. TNHA-SA (°C) @ 10cm, 6/19/22-9/19/22", x = "Air Temperature", y="Ground Temperature (°C) @ 10cm",color="Station") + 
  theme(axis.text.y = element_text(size = 15)) +
  theme(axis.text.x=element_text(angle = 45, hjust = 1.0, size = 15), 
        axis.line = element_line(colour = "black", size =0.5, 
                                 linetype = "solid")) +
  theme(strip.text.y = element_text(size = 15),plot.title = element_text(hjust = 0.5, size = 20), 
        plot.caption = element_text(face ="italic"),
        strip.text = element_text(size = 15),
        axis.title = element_text(size = 15)) +
  theme(axis.title.y = element_text(margin = margin(r=15))) +
  theme(axis.title.x = element_text(margin = margin(t=15))) +
  theme(legend.title = element_text(size = 15),
        legend.text = element_text(size = 10),
        legend.key.height = unit(1,'cm')) +
    geom_smooth(method=lm, se=TRUE)
```

```{r}
XY_grnd_air = averages %>% filter(!sensor == "TNHA-SB", !sensor == "TNHA-SD", !sensor == "TNHA-SA") 
  ggplot(data = XY_grnd_air, aes(x=airtemp, y = grndtmp, color=sensor)) +
  geom_point()+
  theme_bw() + 
    labs(title= "TNHA-BASE vs. TNHA-SC (°C) @ 10cm, 6/19/22-9/19/22", x = "Air Temperature", y="Ground Temperature (°C) @ 10cm",color="Station") + 
  theme(axis.text.y = element_text(size = 15)) +
  theme(axis.text.x=element_text(angle = 45, hjust = 1.0, size = 15), 
        axis.line = element_line(colour = "black", size =0.5, 
                                 linetype = "solid")) +
  theme(strip.text.y = element_text(size = 15),plot.title = element_text(hjust = 0.5, size = 20), 
        plot.caption = element_text(face ="italic"),
        strip.text = element_text(size = 15),
        axis.title = element_text(size = 15)) +
  theme(axis.title.y = element_text(margin = margin(r=15))) +
  theme(axis.title.x = element_text(margin = margin(t=15))) +
  theme(legend.title = element_text(size = 15),
        legend.text = element_text(size = 10),
        legend.key.height = unit(1,'cm')) +
    geom_smooth(method=lm, se=TRUE)
```

```{r}
XY_grnd_air = averages %>% filter(!sensor == "TNHA-BASE", !sensor == "TNHA-SD", !sensor == "TNHA-SB") 
  ggplot(data = XY_grnd_air, aes(x=airtemp, y = grndtmp, color=sensor)) +
  geom_point()+
  theme_bw() + 
    labs(title= "TNHA-SA vs. TNHA-SC (°C) @ 10cm, 6/19/22-9/19/22", x = "Air Temperature", y="Ground Temperature (°C) @ 10cm",color="Station") + 
  theme(axis.text.y = element_text(size = 15)) +
  theme(axis.text.x=element_text(angle = 45, hjust = 1.0, size = 15), 
        axis.line = element_line(colour = "black", size =0.5, 
                                 linetype = "solid")) +
  theme(strip.text.y = element_text(size = 15),plot.title = element_text(hjust = 0.5, size = 20), 
        plot.caption = element_text(face ="italic"),
        strip.text = element_text(size = 15),
        axis.title = element_text(size = 15)) +
  theme(axis.title.y = element_text(margin = margin(r=15))) +
  theme(axis.title.x = element_text(margin = margin(t=15))) +
  theme(legend.title = element_text(size = 15),
        legend.text = element_text(size = 10),
        legend.key.height = unit(1,'cm')) +
    geom_smooth(method=lm, se=TRUE)
```
# see where the data gaps between sensors are occuring for gap filling
```{r}
gap_list_adj = gap_list %>% filter(station == "TNHA", !sensor == "TNHA-SB", !sensor == "TNHA-SC", !sensor == "TNHA-SD")
sideye <- sideye %>%  filter(!sensor == "TNHA-SB", !sensor == "TNHA-SC", !sensor == "TNHA-SD")
sideye %>%
  ggplot() +
  geom_point(aes(x=Date, y = grndtmp, color = sensor)) +
  geom_point(data = gap_list_adj, aes(x = gap_date, y = gap_date, color = sensor))
    theme_bw()
```

```{r}
dataaa <- grndtmp %>% filter(sensor == "TNHA-SA")
ggplot_na_gapsize(dataaa)
```

--- AMPLTIUDE GRAPHS ---

```{r}

XY_grnd_avgs = averages %>% filter(station == "TNHA", !sensor == "TNHA-SA", !sensor == "TNHA-BASE", !sensor == "TNHA-SB") 
  ggplot(data = XY_grnd_avgs, aes(x=airtemp, y = amplitude, color=sensor)) +
  geom_point()+
  theme_bw() + 
    labs(title= "TNHA-SC vs. TNHA-SD (°C) @ 10cm, 6/19/22-9/19/22", x = "Air Temperature", y="Ground Temperature Amplitude (°C) @ 10cm",color="Station") + 
  theme(axis.text.y = element_text(size = 15)) +
  theme(axis.text.x=element_text(angle = 45, hjust = 1.0, size = 15), 
        axis.line = element_line(colour = "black", size =0.5, 
                                 linetype = "solid")) +
  theme(strip.text.y = element_text(size = 15),plot.title = element_text(hjust = 0.5, size = 15), 
        plot.caption = element_text(face ="italic"),
        strip.text = element_text(size = 15),
        axis.title = element_text(size = 15)) +
  theme(axis.title.y = element_text(margin = margin(r=15))) +
  theme(axis.title.x = element_text(margin = margin(t=15))) +
  theme(legend.title = element_text(size = 15),
        legend.text = element_text(size = 10),
        legend.key.height = unit(1,'cm')) +
    geom_smooth(method=lm, se=TRUE)

```
----- WIDE DATA FRAME FOR AIR TEMP COMPARISONS AMONG SENSORS ------

```{r}
wide_airtemp<- averages %>% tidyr::pivot_wider(id_cols = Date, names_from = sensor, values_from = airtemp)
#this isnt necesssary , can IGNORE
```

#air temp vs air temp figures
```{r}

XY_air_avgs = averages %>% filter(station == "TNHA",!sensor == "TNHA-SA", !sensor == "TNHA-SC", !sensor == "TNHA-SB") 
  ggplot(data = XY_air_avgs, aes(x=airtemp, y = airtemp, color=sensor)) +
  geom_point()+
  theme_bw() + 
    labs(title= "Daily Avg., TNHA-BASE vs. TNHA-SD (°C) @ 10cm, 6/19/22-9/19/22", x = "Air Temperature", y="Air Temperature",color="Station") + 
  theme(axis.text.y = element_text(size = 15)) +
  theme(axis.text.x=element_text(angle = 45, hjust = 1.0, size = 15), 
        axis.line = element_line(colour = "black", size =0.5, 
                                 linetype = "solid")) +
  theme(strip.text.y = element_text(size = 15),plot.title = element_text(hjust = 0.5, size = 15), 
        plot.caption = element_text(face ="italic"),
        strip.text = element_text(size = 15),
        axis.title = element_text(size = 15)) +
  theme(axis.title.y = element_text(margin = margin(r=15))) +
  theme(axis.title.x = element_text(margin = margin(t=15))) +
  theme(legend.title = element_text(size = 15),
        legend.text = element_text(size = 10),
        legend.key.height = unit(1,'cm')) +
    geom_smooth(method=lm, se=TRUE)

```


