---
title: "heatmap"
author: "Mirella Shaban"
date: "2024-11-08"
output: html_document
---

Load in data and aggregate by station
------
Load packages
```{r}
library(ggplot2)
library(plyr)
library(dplyr)
library(lubridate)
library(tidyr)
library(gridExtra)
library(forcats)
library(splitstackshape) # basically like text to columns
library(naniar)
library(RColorBrewer)
library(caret)
```

Load gap filled daily average data from GIT
```{r}
filepath = "https://raw.githubusercontent.com/shabanm2/Utqiagvik/main/Meteorological_Seasons_Data/"

gapfilldata = "all_sites_daily_gap_filled.csv"

allvargapfill =read.csv(paste0(filepath, gapfilldata))
```
If no wifi, load through downloads folder:
```{r}
allvargapfill <- all_sites_daily_gap_filled
```


Separate each variable into its own dataframe
```{r}
grndtmp = allvargapfill %>% subset() %>% select(day, fullname, site, station, grounddepth, groundtemp) %>% filter( !grounddepth == "-888.8") 

grndtmp$grounddepth <- as.factor(as.character(grndtmp$grounddepth))
grndtmp$grounddepth <- revalue(grndtmp$grounddepth, c("7" = "3.5cm", "8" = "10cm", "9" = "20cm", "10" = "30cm", "11" = "40cm", "12" = "50cm", "13" = "55cm", "14" = "65cm", "15" = "75cm", "16" = "85cm", "17" = "90cm"))

vwc = allvargapfill %>% subset() %>% select(day, fullname, site, station, grounddepth, vwc) %>% filter( !vwc == "-888.8")

solar = allvargapfill %>% subset() %>% select(day, fullname, site, station, solar) %>% filter( !solar == "-888.8")

air = allvargapfill %>% subset() %>% select(day, fullname, site, station, airtemp) %>% filter( !airtemp == "-888.8")

wind = allvargapfill %>% subset() %>% select(day, fullname, site, station, windspeed, winddir) %>% filter( !winddir == "-888.8", !windspeed == "-888.8")
```


AVERAGE BY STATION (can compare sensors at the same site, such as N & S) by day
```{r}
averaged_by_station <- grndtmp %>% filter(fullname == "TNHA-BASE") %>% aggregate(groundtemp~day+grounddepth, mean)
averaged_by_station$fullname <- c("TNHA-BASE")

averaged_by_station1 <- grndtmp %>% filter(fullname == "TNHA-SA") %>% aggregate(groundtemp~day+grounddepth, mean)
averaged_by_station1$fullname <- c("TNHA-SA")

averaged_by_station2 <- grndtmp %>% filter(fullname == "TNHA-SB") %>% aggregate(groundtemp~day+grounddepth, mean)
averaged_by_station2$fullname <- c("TNHA-SB")

averaged_by_station3 <- grndtmp %>% filter(fullname == "TNHA-SC") %>% aggregate(groundtemp~day+grounddepth, mean)
averaged_by_station3$fullname <- c("TNHA-SC")


averaged_by_station4 <- grndtmp %>% filter(fullname == "TNHA-SD") %>% aggregate(groundtemp~day+grounddepth, mean)
averaged_by_station4$fullname <- c("TNHA-SD")

averaged_by_station5 <- grndtmp %>% filter(fullname == "SSMH-BASE") %>% aggregate(groundtemp~day+grounddepth, mean)
averaged_by_station5$fullname <- c("SSMH-BASE")

averaged_by_station6 <- grndtmp %>% filter(fullname == "SSMH-SA") %>% aggregate(groundtemp~day+grounddepth, mean)
averaged_by_station6$fullname <- c("SSMH-SA")

averaged_by_station7 <- grndtmp %>% filter(fullname == "SSMH-SB") %>% aggregate(groundtemp~day+grounddepth, mean)
averaged_by_station7$fullname <- c("SSMH-SB")


averaged_by_station8 <- grndtmp %>% filter(fullname == "SSMH-SD") %>% aggregate(groundtemp~day+grounddepth, mean)
averaged_by_station8$fullname <- c("SSMH-SD")


averaged_by_station9 <- grndtmp %>% filter(fullname == "SSMH-SE") %>% aggregate(groundtemp~day+grounddepth, mean)
averaged_by_station9$fullname <- c("SSMH-SE")

averaged_by_station10 <- grndtmp %>% filter(fullname == "SSMH-SF") %>% aggregate(groundtemp~day+grounddepth, mean)
averaged_by_station10$fullname <- c("SSMH-SF")

averaged_by_station11 <- grndtmp %>% filter(fullname == "SSMH-SG") %>% aggregate(groundtemp~day+grounddepth, mean)
averaged_by_station11$fullname <- c("SSMH-SG")

averaged_by_station12 <- grndtmp %>% filter(fullname == "SSMH-SH") %>% aggregate(groundtemp~day+grounddepth, mean)
averaged_by_station12$fullname <- c("SSMH-SH")

averaged_by_station13 <- grndtmp %>% filter(fullname == "SSMH-SI") %>% aggregate(groundtemp~day+grounddepth, mean)
averaged_by_station13$fullname <- c("SSMH-SI")

averaged_by_station14 <- grndtmp %>% filter(fullname == "BEO-B05" | fullname == "BEO-B06" | fullname == "BEO-B07" | fullname == "BEO-B08") %>% aggregate(groundtemp~day+grounddepth, mean)
 averaged_by_station14$fullname <- c("BEO")




Daily_grndtmp_avgs<- rbind(averaged_by_station, averaged_by_station1, averaged_by_station2, averaged_by_station3,averaged_by_station4,averaged_by_station5,averaged_by_station6,averaged_by_station7,averaged_by_station9,averaged_by_station8,averaged_by_station11,averaged_by_station13,averaged_by_station14)

Daily_grndtmp_avgs$day <- as.Date(Daily_grndtmp_avgs$day, format= "%Y-%m-%d",tz="UTC")
```

-----
Select / refine criteria

summer 22
```{r}
#data transformation
Daily_grndtmp_avgs$groundtemp <- as.numeric(Daily_grndtmp_avgs$groundtemp)
Daily_grndtmp_avgs$fullname <- as.factor(Daily_grndtmp_avgs$fullname)
Daily_grndtmp_avgs$grounddepth <- Daily_grndtmp_avgs$grounddepth

#depth and station(fullname) constraint
plot1 <- Daily_grndtmp_avgs %>% 
  filter(grounddepth=="10cm" | grounddepth=="30cm" | grounddepth=="55cm" | grounddepth=="65cm" |grounddepth=="90cm") %>% 
  filter(fullname =="BEO" | fullname == "TNHA-BASE" | fullname == "TNHA-SA" |fullname =="TNHA-SB"|fullname =="TNHA-SC" |fullname == "TNHA-SD" |fullname == "SSMH-BASE" |fullname =="SSMH-SA"|fullname =="SSMH-SB" |fullname =="SSMH-SD")  %>% 
  mutate(grounddepth = factor(grounddepth, levels = c("10cm", "30cm", "55cm","65cm", "90cm")))  %>% 
  mutate(fullname = factor(fullname, levels = c("BEO", "TNHA-BASE", "TNHA-SA", "TNHA-SB", "TNHA-SC", "TNHA-SD", "SSMH-BASE", "SSMH-SA", "SSMH-SB", "SSMH-SD")))
```


```{r}
#date constraint
season <- plot1 %>% filter(day >= "2022-06-01" & day <= "2022-09-01")


#rounding and getting seasonal average for each station
season %>%
  group_by(fullname,groundtemp,grounddepth) %>%
  summarize(mean_X1 = mean(groundtemp)) %>% 
  aggregate( groundtemp ~ fullname + grounddepth, mean ) %>%
  group_by(fullname)

season1 <- season %>% 
  group_by(fullname, day) %>%
  aggregate(groundtemp ~fullname + grounddepth, mean)

df_new <- season1 %>% mutate(across(c("groundtemp"), round, 2))

```

Summer 22 plot
```{r fig1, fig.height = 5, fig.width = 8}
#data plotting 
ggplot(df_new, aes(x= grounddepth, y = fullname, fill = groundtemp)) + 
  geom_tile() + 
  scale_fill_gradient2(low= "blue", high = "red") + 
  geom_text(aes(label=groundtemp)) +
theme(legend.title = element_text(size = 15), legend.text = element_text(size = 10)) +
  labs(title = "Summer 2022 Average Ground Temperatures", y = "Station", x= "Depth") +
  theme(axis.text.y =element_text(face="bold",size = 10) ,
        axis.text.x=element_text(angle = 45, hjust = 1.0, face = "bold", size = 10), 
        axis.line = element_line(colour = "black", size =0.5, linetype = "solid")) +
  theme(plot.title = element_text(hjust = 0.5, size = 18),
        axis.title.x = element_text(size = 15),
        axis.title.y = element_text(size = 15)) +
  theme_bw()

```


FALL
```{r}
#date constraint
season <- plot1 %>% filter(day >= "2022-09-01" & day <= "2022-12-01")


#rounding and getting seasonal average for each station
season %>%
  group_by(fullname,groundtemp,grounddepth) %>%
  summarize(mean_X1 = mean(groundtemp)) %>% 
  aggregate( groundtemp ~ fullname + grounddepth, mean ) %>%
  group_by(fullname)

season1 <- season %>% 
  group_by(fullname, day) %>%
  aggregate(groundtemp ~fullname + grounddepth, mean)

df_new <- season1 %>% mutate(across(c("groundtemp"), round, 2))
```

Fall 22 plot
```{r fig2, fig.height = 5, fig.width = 8}
#data plotting 
ggplot(df_new, aes(x= grounddepth, y = fullname, fill = groundtemp)) + 
  geom_tile() + 
  scale_fill_gradient2(low= "blue", high = "red") + 
  geom_text(aes(label=groundtemp)) +
theme(legend.title = element_text(size = 15), legend.text = element_text(size = 10)) +
  labs(title = "Fall 2022 Average Ground Temperatures", y = "Station", x= "Depth") +
  theme(axis.text.y =element_text(face="bold",size = 10) ,
        axis.text.x=element_text(angle = 45, hjust = 1.0, face = "bold", size = 10), 
        axis.line = element_line(colour = "black", size =0.5, linetype = "solid")) +
  theme(plot.title = element_text(hjust = 0.5, size = 18),
        axis.title.x = element_text(size = 15),
        axis.title.y = element_text(size = 15)) +
  theme_bw()
```

SPRING
```{r}
#date constraint
season <- plot1 %>% filter(day >= "2023-03-01" & day <= "2023-06-01")


#rounding and getting seasonal average for each station
season %>%
  group_by(fullname,groundtemp,grounddepth) %>%
  summarize(mean_X1 = mean(groundtemp)) %>% 
  aggregate( groundtemp ~ fullname + grounddepth, mean ) %>%
  group_by(fullname)

season1 <- season %>% 
  group_by(fullname, day) %>%
  aggregate(groundtemp ~fullname + grounddepth, mean)

df_new <- season1 %>% mutate(across(c("groundtemp"), round, 2))
```

Spring 23 plot
```{r fig3, fig.height = 5, fig.width = 8}
#data plotting 
ggplot(df_new, aes(x= grounddepth, y = fullname, fill = groundtemp)) + 
  geom_tile() + 
  scale_fill_gradient2(low= "blue", high = "red") + 
  geom_text(aes(label=groundtemp)) +
theme(legend.title = element_text(size = 15), legend.text = element_text(size = 10)) +
  labs(title = "Spring 2023 Average Ground Temperatures", y = "Station", x= "Depth") +
  theme(axis.text.y =element_text(face="bold",size = 10) ,
        axis.text.x=element_text(angle = 45, hjust = 1.0, face = "bold", size = 10), 
        axis.line = element_line(colour = "black", size =0.5, linetype = "solid")) +
  theme(plot.title = element_text(hjust = 0.5, size = 18),
        axis.title.x = element_text(size = 15),
        axis.title.y = element_text(size = 15)) +
  theme_bw()
```