---
title: "Merge_oldgapfill_newgapfill"
author: "Mirella Shaban"
date: "2026-03-18"
output: html_document
---
#Merge together data from 2022- summer 2024 from all_sites_daily_gap_filled.csv with fall 2024-summer 2025 data from all_var_combined_22_25_BEO_comp_UPDATED.csv

#need to first split each data frame at the data range that I desire, then do a row bind (are they in the same order?)

#SEND TO GRACE WHEN COMPLETE

```{r}

filepath = "https://raw.githubusercontent.com/shabanm2/Utqiagvik/main/Meteorological_Seasons_Data/"

oldgap = "all_sites_daily_gap_filled.csv"
newgap = "all_var_combined_22_25_BEO_COMP_updated.csv"

oldgap = read.csv(paste0(filepath, oldgap))
#need to change column neames to match negap, relate the VWC and groundepths to proper naming (10cm, 0:15cm)
  
newgap = read.csv(paste0(filepath, newgap))
```

```{r}
#oldgap name changes

#old gap vwc / ground depth value changes

#date objects for BOTH df's

# Step 1: Recode vwcdepth in vwc_daily
oldgap$vwcdepth <- recode(as.character(oldgap$vwcdepth), 
                              "1" = "0-15cm", 
                              "2" = "15-30cm", 
                              "3" = "30-45cm",
                              "4" = "45-60cm", 
                              "5" = "60-75cm", 
                              "6" = "75-90cm")
oldgap$grounddepth <- as.character(oldgap$grounddepth)
oldgap$grounddepth <- revalue(oldgap$grounddepth, c("7" = "3.5cm", "8" = "10cm", "9" = "20cm", 
                                           "10" = "30cm", "11" = "40cm", "12" = "50cm", 
                                           "13" = "55cm", "14" = "65cm", "15" = "75cm", 
                                           "16" = "85cm", "17" = "90cm"))

# Step 2: Apply vwcdepth mapping to gt_daily
colnames(oldgap)[6] = "grounddepth"
oldgap <- oldgap %>% 
  mutate(vwcdepth = case_when(
    grounddepth == "3.5cm" ~ "0-15cm",
    grounddepth == "10cm" ~ "0-15cm",
    grounddepth == "20cm" ~ "15-30cm",
    grounddepth == "30cm" ~ "30-45cm",
    grounddepth == "40cm" ~ "30-45cm",
    grounddepth == "50cm" ~ "45-60cm",
    grounddepth == "55cm" ~ "45-60cm",
    grounddepth == "65cm" ~ "60-75cm",
    grounddepth == "75cm" ~ "75-90cm",
    grounddepth == "85cm" ~ "75-90cm",
    grounddepth == "90cm" ~ "75-90cm"
  ))

###Maybe dont have to do this to old gap
# Step 3: Expand BEO-BASE for air, solar, wind ONLY
beo_ground_sensors <- c('BEO-B05', 'BEO-B06', 'BEO-B07', 'BEO-B08')

expand_beo_base <- function(df) {
  beo_base_rows <- df %>% filter(sensor_name == "BEO-BASE")
  non_beo_rows <- df %>% filter(sensor_name != "BEO-BASE")
  
  beo_expanded <- beo_base_rows %>%
    crossing(new_sensor = beo_ground_sensors) %>%
    mutate(sensor_name = new_sensor) %>%
    select(-new_sensor)
  
  bind_rows(non_beo_rows, beo_expanded)
}
```

```{r}
colnames(oldgap)[2] = "Date"
colnames(oldgap)[3] = "sensor_name"
colnames(oldgap)[8] = "ground_temp"
colnames(oldgap)[10] = "air_temp"
colnames(oldgap)[12] = "wind_speed"
colnames(oldgap)[13] = "wind_dir"
oldgap$Date <- as.Date(oldgap$Date, format = "%Y-%m-%d")
newgap$Date <- as.Date(newgap$Date, format = "%Y-%m-%d")
newgap <- separate(newgap, sensor_name, into = c("site", "station"), sep = "-", remove = FALSE)
```

```{r}
#select dates to keep from each dataframe
oldgap_22_24 <- oldgap %>% filter(Date >="2022-06-09" & Date <= "2024-08-31")
newgap_24_25 <- newgap %>% filter(Date >="2024-09-01" & Date <= "2025-08-31")
merged_old_new_gapfill <- rbind(oldgap_22_24, newgap_24_25)

#write.csv(merged_old_new_gapfill, "~/Desktop/UVA/RESEARCH/Barrow/Merged_oldgap_newgap.csv")
#write.csv(merged_old_new_gapfill, "~/Desktop/UVA/RESEARCH/Barrow/GAP_FILLED_CSV_DOWNLOADS/Sep/Merged_oldgap_newgap.csv")

#saved both in gap fill folder and in sep* gap fill folder

```

